baseURL = "https://insomdev.my.id/"
languageCode = "id-ID"
title = "insomdev"
enableEmoji = true
PygmentsCodeFences = true
PygmentsStyle = "monokai"
Paginate = 2

[menu]

  [[menu.main]]
    name = "about"
    url = "/about/"

  [[menu.main]]
    name = "github"
    url = "/getting-started/"