baseURL = "https://insomdev.my.id/"
languageCode = "id-ID"
title = "InsomDev"
enableEmoji = true
PygmentsCodeFences = true
PygmentsStyle = "monokai"
# Paginate = 2
summaryLength = 5

[params]
  description = "Blog yang menyajikan artikel seputar pemgrograman."

[menu]

  [[menu.main]]
    name = "about"
    url = "/about/"

  [[menu.main]]
    name = "github"
    url = "http://github.com/bramaudi"